const db = require('../models/indexStart');
const createError = require('http-errors');
const { accountCreationSchema, transferSchema } = require('../validation/validation_Schema');
const Account = db.accounts;
const Transfer = db.transfers;

module.exports = {
    // Create a new account — uuid is auto-generated by the model hook
    createAccount: async (req, res, next) => {
        try {
            const { error } = accountCreationSchema.validate(req.body);
            if (error) {
                throw createError(400, error.details[0].message);
            }

            const account = await Account.create({
                name: req.body.name,
                balance: req.body.balance,
            });

            res.status(201).json({ success: true, data: account });
        } catch (error) {
            next(error);
        }
    },

    // look up a single account by its public uuid — never by integer id
    getAccountInfo: async (req, res, next) => {
        try {
            const account = await Account.findOne({
                where: { uuid: req.params.uuid },
            });

            if (!account) {
                throw createError(404, 'Account not found');
            }

            res.status(200).json({ success: true, data: account });
        } catch (error) {
            next(error);
        }
    },

    // list every account
    getAllAccounts: async (req, res, next) => {
        try {
            const accounts = await Account.findAll({
                order: [['createdAt', 'DESC']],
            });
            res.status(200).json({ success: true, data: accounts });
        } catch (error) {
            next(error);
        }
    },

    // delete by uuid — balance must be zero first
    deleteAccount: async (req, res, next) => {
        try {
            const account = await Account.findOne({
                where: { uuid: req.params.uuid },
            });

            if (!account) {
                throw createError(404, 'Account not found');
            }

            if (account.balance > 0) {
                throw createError(400, 'Cannot delete an account with a remaining balance. Transfer funds out first.');
            }

            await account.destroy();
            res.status(200).json({ success: true, data: { message: 'Account deleted successfully' } });
        } catch (error) {
            next(error);
        }
    },

    // summary stats for the dashboard
    getStats: async (req, res, next) => {
        try {
            const totalAccounts = await Account.count();
            const totalTransfers = await Transfer.count();

            const balanceResult = await Account.findOne({
                attributes: [[db.sequelize.fn('SUM', db.sequelize.col('balance')), 'total']],
                raw: true,
            });
            const totalBalance = parseFloat(balanceResult?.total) || 0;

            const recentTransfers = await Transfer.findAll({
                limit: 5,
                order: [['createdAt', 'DESC']],
                include: [
                    { model: Account, as: 'sender', attributes: ['uuid', 'name'] },
                    { model: Account, as: 'receiver', attributes: ['uuid', 'name'] },
                ],
            });

            res.status(200).json({
                success: true,
                data: { totalAccounts, totalTransfers, totalBalance, recentTransfers },
            });
        } catch (error) {
            next(error);
        }
    },

    // transfer — frontend sends uuids, we resolve them to integer ids internally
    createTransfer: async (req, res, next) => {
        const { error } = transferSchema.validate(req.body);
        if (error) {
            return res.status(400).json({ error: { message: error.details[0].message } });
        }

        const { from_account_uuid, to_account_uuid, amount } = req.body;
        const transaction = await db.sequelize.transaction();

        try {
            // resolve uuids to actual account rows
            const fromAccount = await Account.findOne({ where: { uuid: from_account_uuid } });
            const toAccount = await Account.findOne({ where: { uuid: to_account_uuid } });

            if (!fromAccount || !toAccount) {
                throw createError(404, 'One or both accounts not found');
            }

            // edge case: can't transfer to yourself
            if (fromAccount.id === toAccount.id) {
                throw createError(400, 'Cannot transfer funds to the same account');
            }

            if (fromAccount.balance < amount) {
                throw createError(400, 'Insufficient funds');
            }

            await fromAccount.update({ balance: fromAccount.balance - amount }, { transaction });
            await toAccount.update({ balance: toAccount.balance + amount }, { transaction });

            // store the internal integer ids in the transfer record — that's what the FK expects
            const transfer = await Transfer.create(
                { from_account_id: fromAccount.id, to_account_id: toAccount.id, amount },
                { transaction }
            );

            await transaction.commit();
            res.status(200).json({ success: true, data: transfer });
        } catch (error) {
            await transaction.rollback();
            next(error);
        }
    },

    // full transfer list with sender and receiver names
    getAllTransfers: async (req, res, next) => {
        try {
            const transfers = await Transfer.findAll({
                order: [['createdAt', 'DESC']],
                include: [
                    { model: Account, as: 'sender', attributes: ['uuid', 'name'] },
                    { model: Account, as: 'receiver', attributes: ['uuid', 'name'] },
                ],
            });
            res.status(200).json({ success: true, data: transfers });
        } catch (error) {
            next(error);
        }
    },
};
